//
// ActionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ActionsAPI {

    /**
     Добавить действие
     
     - parameter newRepeatableAction: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RepeatableAction
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addAction(newRepeatableAction: NewRepeatableAction? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RepeatableAction {
        return try await addActionWithRequestBuilder(newRepeatableAction: newRepeatableAction, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Добавить действие
     - POST /actions/add/
     - Добавить действие
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter newRepeatableAction: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RepeatableAction> 
     */
    open class func addActionWithRequestBuilder(newRepeatableAction: NewRepeatableAction? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RepeatableAction> {
        let localVariablePath = "/actions/add/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: newRepeatableAction, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RepeatableAction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Изменить действие
     
     - parameter actionid: (path) Id искомого действия 
     - parameter repeatableAction: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RepeatableAction
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func editAction(actionid: Int, repeatableAction: RepeatableAction? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RepeatableAction {
        return try await editActionWithRequestBuilder(actionid: actionid, repeatableAction: repeatableAction, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Изменить действие
     - POST /actions/{actionid}/
     - Изменить действие
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter actionid: (path) Id искомого действия 
     - parameter repeatableAction: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RepeatableAction> 
     */
    open class func editActionWithRequestBuilder(actionid: Int, repeatableAction: RepeatableAction? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RepeatableAction> {
        var localVariablePath = "/actions/{actionid}/"
        let actionidPreEscape = "\(APIHelper.mapValueToPathItem(actionid))"
        let actionidPostEscape = actionidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{actionid}", with: actionidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: repeatableAction, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RepeatableAction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Получить действие по id
     
     - parameter actionid: (path) Id искомого действия 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RepeatableAction
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAction(actionid: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RepeatableAction {
        return try await getActionWithRequestBuilder(actionid: actionid, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Получить действие по id
     - GET /actions/{actionid}/
     - Получить действие по id
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter actionid: (path) Id искомого действия 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RepeatableAction> 
     */
    open class func getActionWithRequestBuilder(actionid: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RepeatableAction> {
        var localVariablePath = "/actions/{actionid}/"
        let actionidPreEscape = "\(APIHelper.mapValueToPathItem(actionid))"
        let actionidPostEscape = actionidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{actionid}", with: actionidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RepeatableAction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Получить список всех действий
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [RepeatableAction]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAllActions(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> [RepeatableAction] {
        return try await getAllActionsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Получить список всех действий
     - GET /actions/
     - Получить список всех действий
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[RepeatableAction]> 
     */
    open class func getAllActionsWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<[RepeatableAction]> {
        let localVariablePath = "/actions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RepeatableAction]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
