//
// ErrorObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ErrorObject: Sendable, Codable, ParameterConvertible, Hashable {

    public var message: String
    public var responseNumber: Int

    public init(message: String, responseNumber: Int) {
        self.message = message
        self.responseNumber = responseNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case responseNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(responseNumber, forKey: .responseNumber)
    }
}

