//
// RepeatableAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RepeatableAction: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: UUID
    public var title: String
    public var maxRepeats: Int
    public var currentRepeats: Int

    public init(id: UUID, title: String, maxRepeats: Int, currentRepeats: Int) {
        self.id = id
        self.title = title
        self.maxRepeats = maxRepeats
        self.currentRepeats = currentRepeats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case maxRepeats
        case currentRepeats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(maxRepeats, forKey: .maxRepeats)
        try container.encode(currentRepeats, forKey: .currentRepeats)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RepeatableAction: Identifiable {}
