//
// NewRepeatableAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NewRepeatableAction: Sendable, Codable, ParameterConvertible, Hashable {

    public var title: String
    public var maxRepeats: Int
    public var currentRepeats: Int

    public init(title: String, maxRepeats: Int, currentRepeats: Int) {
        self.title = title
        self.maxRepeats = maxRepeats
        self.currentRepeats = currentRepeats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case maxRepeats
        case currentRepeats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(maxRepeats, forKey: .maxRepeats)
        try container.encode(currentRepeats, forKey: .currentRepeats)
    }
}

